version: '2'
services:
  web:
    image: odoo:13.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    labels:
      - traefik.enable=true
      - traefik.backend=project-freedom-odoo
      - traefik.frontend.rule=Host:odoo.projectfreedom.test
      - traefik.docker.network=web
    networks:
      - internal
      - web


  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    labels:
      - "traefik.enable=false"
    networks:
      - internal

volumes:
  odoo-web-data:
  odoo-db-data:

networks:
  internal:
    external: false
  web:
    external: true
